config/routes.rb
Rails.application.routes.draw do
  resources :hookups

  root 'hookups#welcome'
  get '/contact', to: 'hookups#contact'
end

app/models/hookup.rb
class Hookup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hookups_controller.rb
class HookupsController < ApplicationController
  before_action :set_hookup, only: [:show, :edit, :update, :destroy]

  # GET /hookups
  # GET /hookups.json
  def index
    @hookups = Hookup.all
  end

  # GET /hookups/1
  # GET /hookups/1.json
  def show
    @hookup = Hookup.find(params[:id])
    @hookup.composite_score = @hookup.personality + @hookup.level_of_attraction + @hookup.intenseness_of_orgasm + @hookup.dick
    if @hookup.did_you_cum then
      @hookup.composite_score += 5
    end
    if @hookup.did_you_cuddle_afterwards then
      @hookup.composite_score += 5
    end
    @hookup.save
  end

  # GET /hookups/new
  def new
    @hookup = Hookup.new
  end

  # GET /hookups/1/edit
  def edit
  end

  # POST /hookups
  # POST /hookups.json
  def create
    @hookup = Hookup.new(hookup_params)

    respond_to do |format|
      if @hookup.save
        format.html { redirect_to @hookup, notice: 'Hookup was successfully created.' }
        format.json { render :show, status: :created, location: @hookup }
      else
        format.html { render :new }
        format.json { render json: @hookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hookups/1
  # PATCH/PUT /hookups/1.json
  def update
    respond_to do |format|
      if @hookup.update(hookup_params)
        format.html { redirect_to @hookup, notice: 'Hookup was successfully updated.' }
        format.json { render :show, status: :ok, location: @hookup }
      else
        format.html { render :edit }
        format.json { render json: @hookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hookups/1
  # DELETE /hookups/1.json
  def destroy
    @hookup.destroy
    respond_to do |format|
      format.html { redirect_to hookups_url, notice: 'Hookup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hookup
      @hookup = Hookup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hookup_params
      params.require(:hookup).permit(:name, :age, :personality, :level_of_attraction, :intenseness_of_orgasm, :dick, :did_you_cum, :did_you_cuddle_afterwards, :composite_score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hookups_helper.rb
module HookupsHelper
end

app/views/hookups/_form.html.erb
<br><br>
<%= form_for(@hookup) do |f| %>
  <br>
  <div class="field">
    <label for="hookup_name">Name</label>
    <br>
    <input type="text" size="40" id="hookup_name" name="hookup[name]">
  </div>
  <div class="field">
    <label for="hookup_age">Age</label>
    <br>
    <input type="number" style="width:40px;" id="hookup_age" name="hookup[age]">
  </div>
  <div class="field">
    <label>Personality</label><br>
  <input type="radio" name="hookup[personality]" id="hookup_personality1" value="1">1
  <input type="radio" name="hookup[personality]" id="hookup_personality2" value="2">2
  <input type="radio" name="hookup[personality]" id="hookup_personality3" value="3">3
  <input type="radio" name="hookup[personality]" id="hookup_personality4" value="4">4
  <input type="radio" name="hookup[personality]" id="hookup_personality5" value="5">5
  </div>
  <div class="field">
    <label>Level of attraction</label><br>
  <input type="radio" name="hookup[level_of_attraction]" id="hookup_level_of_attraction1" value="1">1
  <input type="radio" name="hookup[level_of_attraction]" id="hookup_level_of_attraction2" value="2">2
  <input type="radio" name="hookup[level_of_attraction]" id="hookup_level_of_attraction3" value="3">3
  <input type="radio" name="hookup[level_of_attraction]" id="hookup_level_of_attraction4" value="4">4
  <input type="radio" name="hookup[level_of_attraction]" id="hookup_level_of_attraction5" value="5">5
  </div>
  <div class="field">
    <label>Intenseness of orgasm</label><br>
  <input type="radio" name="hookup[intenseness_of_orgasm]" id="hookup_intenseness_of_orgasm1" value="1">1
  <input type="radio" name="hookup[intenseness_of_orgasm]" id="hookup_intenseness_of_orgasm2" value="2">2
  <input type="radio" name="hookup[intenseness_of_orgasm]" id="hookup_intenseness_of_orgasm3" value="3">3
  <input type="radio" name="hookup[intenseness_of_orgasm]" id="hookup_intenseness_of_orgasm4" value="4">4
  <input type="radio" name="hookup[intenseness_of_orgasm]" id="hookup_intenseness_of_orgasm5" value="5">5
  </div>
  <div class="field">
    <label>Dick</label><br>
  <input type="radio" name="hookup[dick]" id="hookup_dick1" value="1">1
  <input type="radio" name="hookup[dick]" id="hookup_dick2" value="2">2
  <input type="radio" name="hookup[dick]" id="hookup_dick3" value="3">3
  <input type="radio" name="hookup[dick]" id="hookup_dick4" value="4">4
  <input type="radio" name="hookup[dick]" id="hookup_dick5" value="5">5
  </div>
  <div class="field">
    <label>Did you cum?</label>
    <input class="unindent"type="checkbox" name="hookup[did_you_cum]">
  </div>
  <div class="field">
    <label>Did you cuddle afterwards?</label>
    <input class="unindent" type="checkbox" name="hookup[did_you_cuddle_afterwards]">
  </div>
  <%= f.submit %>
<% end %>
<hr>

app/views/hookups/contact.html.erb
<div id="homeContent" style="padding-left:3vw;">
  <div id="welcomeText">
    <h2 id="welcome">Contact</h2>
    <p class="p-bigger">
      Created by Hank Hester
    </p>
    <img src="assets/hank.jpg" style="width:40%;"/>
    <p>
      The University of North Carolina at Chapel Hill<br>
      B.A. Linguistics and Computer Science, Class of 2019<br>
      Email: hankhester1@gmail.com<br>
      Phone: 704-775-2063
    </p>
  </div>
  <div id="getStarted">
      <button type="checkbox" id="button" class="hidden"></button>
      <label for="button" class="button">Get Started</label>
  </div>
</div>

app/views/hookups/edit.html.erb
<h1>Editing Hookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @hookup %> |
<%= link_to 'Back', hookups_path %>

app/views/hookups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Hookups</h1>
<br><br><br><br>
<table class="tbl-all-hookups">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Personality</th>
      <th>Level of attraction</th>
      <th>Intenseness of orgasm</th>
      <th>Dick</th>
      <th>Did you cum</th>
      <th>Did you cuddle afterwards</th>
      <th>Composite score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hookups.each do |hookup| %>
      <tr>
        <td><%= hookup.name %></td>
        <td><%= hookup.age %></td>
        <td><%= hookup.personality %></td>
        <td><%= hookup.level_of_attraction %></td>
        <td><%= hookup.intenseness_of_orgasm %></td>
        <td><%= hookup.dick %></td>
        <td><%= hookup.did_you_cum %></td>
        <td><%= hookup.did_you_cuddle_afterwards %></td>
        <td><%= hookup.composite_score %></td>
        <td><%= link_to 'View', hookup %></td>
        <td><%= link_to 'Edit', edit_hookup_path(hookup) %></td>
        <td><%= link_to 'Delete', hookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hookup', new_hookup_path %>

app/views/hookups/new.html.erb
<div class="content">
  <h1 class="subtitle">New Hookup</h1>
  <br>
<%= render 'form' %>

<%= link_to 'Back', hookups_path %>
</div>

app/views/hookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hookup.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @hookup.age %>
</p>

<p>
  <strong>Personality:</strong>
  <%= @hookup.personality %>
</p>

<p>
  <strong>Level of attraction:</strong>
  <%= @hookup.level_of_attraction %>
</p>

<p>
  <strong>Intenseness of orgasm:</strong>
  <%= @hookup.intenseness_of_orgasm %>
</p>

<p>
  <strong>Dick:</strong>
  <%= @hookup.dick %>
</p>

<p>
  <strong>Did you cum:</strong>
  <%= @hookup.did_you_cum %>
</p>

<p>
  <strong>Did you cuddle afterwards:</strong>
  <%= @hookup.did_you_cuddle_afterwards %>
</p>

<p>
  <strong>Composite score:</strong>
  <%= @hookup.composite_score %>
</p>

<%= link_to 'Edit', edit_hookup_path(@hookup) %> |
<%= link_to 'Back', hookups_path %>

app/views/hookups/welcome.html.erb
<div id="homeContent">
  <div id="welcomeText">
    <h2 id="welcome">Welcome</h2>
    <p class="p-bigger">
      HookUpr is a handy website to track all of your intimate encounters. Whether you need to remember their name at a party, or if you simply want to be able to reminisce about old times, Hookupr is the place for you.
    </p>
  </div>
  <div id="getStarted">
      <button type="checkbox" id="button" class="hidden"></button>
      <label for="button" class="button">Get Started</label>
  </div>
</div>
<script type="text/javascript">
document.getElementById("button").addEventListener("click", goToHookupr);
function goToHookupr() {
window.location.href="/hookups/new";
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HookUpr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
        <div id="nav">
          <div class="navClass" id="logo"><a href="/hookups"><img src="/assets/tinyLogo.png" alt="logo"/></a></div>
          <h1 class="nav-title">HookUpr</h1>
          <div id="navItems">
          <div class="navClass" id="home"><a href="/hookups">Home</a></div>
          <div class="navClass" id="about"><a href="/">About</a></div>
          <div class="navClass" id="contact"><a href="/contact">Contact</a></div>
        </div>
          <!-- TODO: Add menu button -->
        </div>
      </header>

<%= yield %>

</body>
</html>